spring:
  application:
    name: site
  datasource:
    url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1521)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=gb91286f3a5c4e2_oracledb_medium.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
    username: admin
    password: '!@private1AB'
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create