-- users 테이블
CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password VARCHAR2(200),
    email VARCHAR2(200) UNIQUE NOT NULL,
    name VARCHAR2(100),
    role VARCHAR2(50) DEFAULT 'ROLE_USER',
    provider VARCHAR2(50) DEFAULT 'local',
    provider_id VARCHAR2(200),
    enabled NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- verification_tokens
CREATE TABLE verification_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR2(200) NOT NULL,
    user_id NUMBER NOT NULL,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_token_user FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE login_history (
                               id BIGINT PRIMARY KEY AUTO_INCREMENT,
                               username VARCHAR(100),
                               success BOOLEAN,
                               ip VARCHAR(50),
                               timestamp TIMESTAMP
);

-- 게시글 CRUD 기록
CREATE TABLE board_history (
                               id BIGINT PRIMARY KEY AUTO_INCREMENT,
                               board_id BIGINT,
                               username VARCHAR(100),
                               action VARCHAR(50),   -- CREATE, UPDATE, DELETE
                               timestamp TIMESTAMP
);

-- 게시글 조회 기록
CREATE TABLE board_view_history (
                                    id BIGINT PRIMARY KEY AUTO_INCREMENT,
                                    board_id BIGINT,
                                    username VARCHAR(100),
                                    ip VARCHAR(50),
                                    timestamp TIMESTAMP
);